### ISSUE TITLE
Fresh install of PandaCSS with Remix

### ISSUE THREAD

**Issue by ranyefet** [chakra-ui/panda#1114]
### Description

I just follow the installing guide step by step on how to install PandaCSS into Remix app.

It looks like everything is working, but I see some weird error that I can't understand.
When navigating to `http://localhost:3000` I see the following error in the console:

```
ErrorResponse {
  status: 404,
  statusText: 'Not Found',
  internal: true,
  data: 'Error: No route matches URL "/app/%3Cno%20source%3E"',
  error: Error: No route matches URL "/app/%3Cno%20source%3E"
      at getInternalRouterError (/Users/ranyefet/Code/filecraft/node_modules/@remix-run/router/router.ts:4132:5)
      at Object.query (/Users/ranyefet/Code/filecraft/node_modules/@remix-run/router/router.ts:2631:19)
      at handleDocumentRequestRR (/Users/ranyefet/Code/filecraft/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
      at requestHandler (/Users/ranyefet/Code/filecraft/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at /Users/ranyefet/Code/filecraft/node_modules/@remix-run/express/dist/server.js:39:28
}
No routes matched location "/app/%3Cno%20source%3E"
```

### Link to Reproduction

https://stackblitz.com/edit/remix-run-remix-189x6r?file=postcss.config.cjs

### Steps to reproduce

1. [Follow this guide](https://panda-css.com/docs/installation/remix)
2. Open localhost:3000
3. See error the error in the terminal

I tried to reproduce the issue on stackblitz but I couldn't. I even downloaded the project that working on stackblitz and tried running locally but got the same error.

### JS Framework

React, Remix, TS

### Panda CSS Version

0.8.0

### Browser

Firefox

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Node v20.3.1

**Comment by ranyefet** [comment]
Okay, I think I found the issue this is the generated source map for `index.css`

```json
{
  "version": 3,
  "sources": ["../../../app/index.css", "../../../app/<no source>"],
  "sourcesContent": ["@layer reset, base, tokens, recipes, utilities;\n", null],
  "mappings": "...",
  "names": []
}
```

You can see the `sources` property have some reference to `"../../../app/<no source>"` not sure how that got there.

**Comment by nightgrey** [comment]
I also have that issue occasionally, but haven't debugged it further - just wanted to say it's happening to me, too!

**Comment by muco-rolle** [comment]
Would also confirm that I get the same error

**Comment by astahmer** [comment]
This looks like a PostCSS/Remix specific issue, please transfer this issue there as this seems out of scope for us
