### ISSUE TITLE
npx panda init --postcss crash

### ISSUE THREAD

**Issue by anbari1337** [chakra-ui/panda#1587]
### Description

when I run `npx panda init --postcss` it gives me the error below. even when I install the mentioned package, it keeps complaining about other ones.

```
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'pirates'
Require stack:
- /home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/symlink/src/index.js
- /home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/dev/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at symlink (/home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/symlink/src/index.js:8:19)
    at Object.<anonymous> (/home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/dev/bin.js:17:22)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/symlink/src/index.js',
    '/home/amine/Desktop/amine/micro-spotify/node_modules/@pandacss/dev/bin.js'
  ]
}
```

### JS Framework

Next(Ts)

**Comment by astahmer** [comment]
yes sorry, this is a regression introduced in version `0.17.1`, a fix is coming here https://github.com/chakra-ui/panda/pull/1586
version 0.17.0 is fine in the meantime
