### ISSUE TITLE
Error After upgrading to `v0.32.0` or `v0.32.1` from `v0.31.0`

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/panda#2259]
### Description

After upgrading to v0.32.1 or v0.32.1 from v0.31.0, I get this error on Storybook start:

```txt
6:42:59 PM [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'raw')
  Plugin: vite:css
  File: /path/to/project/src/index.css
      at Conditions.get (/path/to/project/node_modules/@pandacss/core/dist/index.js:440:20)
      at /path/to/project/node_modules/@pandacss/generator/dist/index.js:3774:52
      at Array.map (<anonymous>)
      at generateTokenCss (/path/to/project/node_modules/@pandacss/generator/dist/index.js:3774:27)
      at /path/to/project/node_modules/@pandacss/generator/dist/index.js:3848:118
      at t.with (/path/to/project/node_modules/ts-pattern/dist/index.cjs:1:9497)
      at PandaContext.appendCssOfType (/path/to/project/node_modules/@pandacss/generator/dist/index.js:3848:101)
      at PandaContext.appendBaselineCss (/path/to/project/node_modules/@pandacss/generator/dist/index.js:3859:12)
      at Builder.write (/path/to/project/node_modules/@pandacss/node/dist/index.js:2753:9)
      at plugins (/path/to/project/node_modules/@pandacss/postcss/dist/index.js:72:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async LazyResult.runAsync (/path/to/project/node_modules/postcss/lib/lazy-result.js:261:11)
      at async compileCSS (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:38903:25)
      at async TransformContext.transform (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:38300:56)
      at async Object.transform (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:44352:30)
      at async loadAndTransform (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:55026:29)
      at async viteTransformMiddleware (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-68d1a114.js:64430:32)
```

Content of `src/index.css`:

```css
@layer reset, base, tokens, recipes, utilities;
```

the `@pandacss/core/dist/index.js:440:20`:

![Screenshot 2024-02-26 at 18 46 01](https://github.com/chakra-ui/panda/assets/22872117/4eca82a1-939c-4f88-98a0-18991383172f)

### Link to Reproduction

httsp://nolink

### Steps to reproduce

1. Updating `v0.31.0` to `v0.32.0` or `v0.32.1`

### Panda CSS Version

v0.32.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Although I think it has nothing to do with `vite` or `storybook` version, but here is the storybook (and the internal `vite`) version:

- Storybook version: `v7.6.17`

_No response_

**Comment by astahmer** [comment]
I know how to fix but I'd be curious to know what triggered this
