### ISSUE TITLE
RangeError: Map maximum size exceeded

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/panda#2893]
### Description

Hi, 
I don't know what happend but somehow I start to get this error from panda and it stopped generating styled. 

```bash
error [file:extract] RangeError: Map maximum size exceeded
    at Map.set (<anonymous>)
    at ForgetfulNodeCache.set (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@ts-morph+common@0.22.0/node_modules/@ts-morph/common/dist/ts-morph-common.js:71:26)
    at ForgetfulNodeCache.getOrCreate (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@ts-morph+common@0.22.0/node_modules/@ts-morph/common/dist/ts-morph-common.js:60:18)
    at ForgetfulNodeCache.getOrCreate (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:19238:22)
    at CompilerFactory.getNodeFromCompilerNode (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:19624:32)
    at SourceFile._getNodeFromCompilerNode (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:4076:46)
    at /Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:11320:45
    at Array.map (<anonymous>)
    at SourceFile.getStatements (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:11320:31)
    at SourceFile.getImportDeclarations (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/ts-morph@21.0.1/node_modules/ts-morph/dist/ts-morph.js:9300:25)
    at getImportDeclarations (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+parser@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/parser/dist/index.js:64:14)
    at Project.parse2 [as parser] (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+parser@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/parser/dist/index.js:235:32)
    at Project.parseSourceFile (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+parser@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/parser/dist/index.js:639:25)
    at PandaContext.parseFile (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+node@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/node/dist/index.js:2558:29)
    at Builder.extractFile (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+node@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/node/dist/index.js:2826:30)
    at /Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+node@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/node/dist/index.js:2839:30
    at Array.map (<anonymous>)
    at Builder.extract (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+node@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/node/dist/index.js:2839:11)
    at plugins (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/@pandacss+postcss@0.46.1_jsdom@25.0.0_typescript@5.6.2/node_modules/@pandacss/postcss/dist/index.js:64:17)
    at async LazyResult.runAsync (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/postcss@8.4.31/node_modules/postcss/lib/lazy-result.js:261:11)
    at async Span.traceAsyncFn (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async /Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js:54:22
    at async Span.traceAsyncFn (/Users/omarkhatib/GitHub/usemando.ai/node_modules/.pnpm/next@14.2.13_@babel+core@7.25.2_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
```

### Link to Reproduction

it's really hard to provide a repo to produce the same error

### Steps to reproduce

there is none

### JS Framework

React (TS)

### Panda CSS Version

0.46.0 and 0.46.1

### Browser

Latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by omarkhatibco** [comment]
I just noticed that styled does not work anymore 

![Screenshot 2024-09-24 at 03 12 13](https://github.com/user-attachments/assets/bb8dc844-1a12-4fb6-a470-bc4557179e48)
