### ISSUE TITLE
NextJS build fails occasionally leading to corrupted styles

### ISSUE THREAD

**Issue by mrchrishahn** [chakra-ui/panda#3027]
### Description

We're using Panda with Park UI in our NextJS app that we deploy on Vercel. It occasionally happens that the build silently fails (it doesn't get interrupted) and the recipe styles don't get applied at all.

Here is the error we get in this case:
```
🐼 error [file:extract] TypeError: import_ts_morph.Node.isSatisfiesExpression is not a function
    at unwrapExpression (/vercel/path0/node_modules/@pandacss/extractor/dist/index.js:86:28)
    at extractJsxSpreadAttributeValues (/vercel/path0/node_modules/@pandacss/extractor/dist/index.js:1316:16)
    at /vercel/path0/node_modules/@pandacss/extractor/dist/index.js:1378:28
    at nodeCallback (/vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3253:33)
    at /vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3288:37
    at Node.forEachChild (/vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3233:37)
    at forEachChildForNode (/vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3287:33)
    at nodeCallback (/vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3261:24)
    at /vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3288:37
    at JsxOpeningElement.forEachChild (/vercel/path0/node_modules/ts-morph/dist/ts-morph.js:3233:37) 
```

We get about 200 of this specific error logs during the build. 

In the end, the final panda log is however: `🐼 info [hrtime] Extracted in (718.83ms)`

Here's an image of the failed build on the left and the successful one on the right. 
![image](https://github.com/user-attachments/assets/1dbe5bbd-6a84-4aa0-8a19-49e4af59b0e9)

### Link to Reproduction

Not possible

### Steps to reproduce

The error doesn't always occur. Typically a redeploy will solve it. 

### JS Framework

NextJS 15.0.4 - Typescript

### Panda CSS Version

0.48.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by mrchrishahn** [comment]
It may have something to do with the build cache and using a new panda version (even if its just a minor one)
